import type { Folder, MockDocument } from "./types";

export const mockDocuments: MockDocument[] = [
  {
    id: "financial-report-q2",
    title: "Financial Performance Report Q2",
    extension: "PDF",
    section: "Home",
    folder: "FY 2026 Reports",
    subject: "For review and approval",
    description: "Quarterly performance report with expenditure, variance, and collection summaries.",
    classification: "Unclassified",
    size: "2.4 MB",
    uploadedAt: "Today, 10:32 AM",
    uploadedBy: "Alex Rivera",
    version: "2.0",
    barcode: "SDL-2026-000184",
    status: "Review",
    recipients: ["Maria Santos", "Victor Tan", "Nina Cruz"],
    viewedBy: ["Maria Santos", "Victor Tan", "Nina Cruz"],
    metadata: [],
  },
  {
    id: "procurement-proposal-q3",
    title: "Procurement Proposal - Q3",
    extension: "PDF",
    section: "Private",
    folder: "Procurement 2026",
    subject: "Procurement committee approval",
    description: "Proposed procurement plan for third-quarter operational requirements.",
    classification: "Classified",
    size: "1.8 MB",
    uploadedAt: "Yesterday, 3:10 PM",
    uploadedBy: "Amelia Reyes",
    version: "1.2",
    barcode: "SDL-2026-000181",
    status: "Pending",
    recipients: ["Luis Mendoza", "Grace Lim"],
    viewedBy: ["Luis Mendoza"],
    metadata: [],
  },
  {
    id: "budget-requirements-2026",
    title: "Budget Requirements 2026",
    extension: "XLSX",
    section: "Private",
    folder: "Budget Management",
    subject: "Budget review",
    description: "Department budget requirements and supporting schedules for fiscal year 2026.",
    classification: "Classified",
    size: "896 KB",
    uploadedAt: "Aug 29, 2026",
    uploadedBy: "Victor Tan",
    version: "3.0",
    barcode: "SDL-2026-000176",
    status: "Setback",
    recipients: ["Maria Santos", "Jamie Flores"],
    viewedBy: ["Maria Santos"],
    metadata: [],
  },
  {
    id: "annual-disclosure",
    title: "Annual Disclosure Notice",
    extension: "DOCX",
    section: "Public",
    folder: "Corporate Notices",
    subject: "For information",
    description: "Public disclosure notice prepared for organization-wide distribution.",
    classification: "Unclassified",
    size: "428 KB",
    uploadedAt: "Aug 27, 2026",
    uploadedBy: "Nina Cruz",
    version: "1.0",
    barcode: "SDL-2026-000169",
    recipients: [],
    viewedBy: ["Alex Rivera", "Maria Santos", "Nina Cruz"],
    metadata: [],
  },
  {
    id: "technical-presentation",
    title: "Technical Presentation",
    extension: "PPTX",
    section: "Home",
    folder: "Meeting Materials",
    subject: "For review",
    description: "Presentation for the upcoming technical steering committee meeting.",
    classification: "Unclassified",
    size: "4.1 MB",
    uploadedAt: "Aug 26, 2026",
    uploadedBy: "Alex Rivera",
    version: "1.1",
    barcode: "SDL-2026-000165",
    status: "Completed",
    recipients: ["Maria Santos", "Victor Tan"],
    viewedBy: ["Maria Santos", "Victor Tan"],
    metadata: [],
  },
  {
    id: "dms-modernization-charter",
    title: "DMS Modernization Charter",
    extension: "DOCX",
    section: "Home",
    folder: "Strategic Initiatives",
    subject: "Project charter review",
    description: "Project charter for the document management system modernization program.",
    classification: "Unclassified",
    size: "742 KB",
    uploadedAt: "Aug 22, 2026",
    uploadedBy: "Alex Rivera",
    version: "1.0",
    barcode: "SDL-2026-000158",
    status: "Pending",
    recipients: ["Amelia Reyes", "Grace Lim"],
    viewedBy: ["Amelia Reyes"],
    metadata: [],
  },
];

export const mockFolders: Folder[] = [
  { id: "fy-2026-reports", name: "FY 2026 Reports", section: "Home", documentCount: 18, updatedAt: "Today" },
  { id: "meeting-materials", name: "Meeting Materials", section: "Home", documentCount: 9, updatedAt: "Yesterday" },
  { id: "strategic-initiatives", name: "Strategic Initiatives", section: "Home", documentCount: 12, updatedAt: "Aug 28" },
  { id: "procurement-2026", name: "Procurement 2026", section: "Private", documentCount: 24, updatedAt: "Today" },
  { id: "budget-management", name: "Budget Management", section: "Private", documentCount: 31, updatedAt: "Yesterday" },
  { id: "executive-council", name: "Executive Council", section: "Private", documentCount: 14, updatedAt: "Aug 30" },
  { id: "corporate-notices", name: "Corporate Notices", section: "Public", documentCount: 16, updatedAt: "Today" },
  { id: "annual-disclosures", name: "Annual Disclosures", section: "Public", documentCount: 8, updatedAt: "Aug 25" },
  { id: "news-and-advisories", name: "News & Advisories", section: "Public", documentCount: 11, updatedAt: "Aug 21" },
];
