"use client";

import { Alert, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import type { MRT_ColumnDef, MRT_PaginationState, MRT_SortingState } from "material-react-table";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { AuthenticatedUser } from "@/features/auth/types";
import { findGroupCandidates, findUserCandidates, getPermissionGrants, grantGroupPermission, grantUserPermission, listPermissions, PermissionsRequestError, revokeGroupPermission, revokeUserPermission } from "@/services/permissions";
import type { ManagedPermission, PermissionGrants, PermissionGroup, PermissionsResult, PermissionUser } from "../permissions.types";
import { PageHeader } from "./admin-page-primitives";
import { SaileAdminTable } from "./saile-admin-table";

const errorMessage = (error: unknown) => error instanceof Error ? error.message : "The request could not be completed.";

function GrantsDialog({ permission, canGrantGroups, canGrantUsers, canRevoke, onClose, onChanged, onSignOut }: {
  permission: ManagedPermission; canGrantGroups: boolean; canGrantUsers: boolean; canRevoke: boolean; onClose: () => void; onChanged: () => void; onSignOut: () => void;
}) {
  const [tab, setTab] = useState<"groups" | "users">("groups"); const [grants, setGrants] = useState<PermissionGrants>({ groups: [], users: [] });
  const [groupCandidates, setGroupCandidates] = useState<PermissionGroup[]>([]); const [userCandidates, setUserCandidates] = useState<PermissionUser[]>([]);
  const [groupId, setGroupId] = useState(""); const [userId, setUserId] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refresh = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(""); try {
    const [current, groups, users] = await Promise.all([getPermissionGrants(permission.id, signal), canGrantGroups ? findGroupCandidates(permission.id, search, signal) : Promise.resolve([]), canGrantUsers ? findUserCandidates(permission.id, search, signal) : Promise.resolve([])]);
    setGrants(current); setGroupCandidates(groups); setUserCandidates(users);
  } catch (error) { if (error instanceof PermissionsRequestError && error.status === 401) onSignOut(); setError(errorMessage(error)); } finally { setLoading(false); } }, [permission.id, search, canGrantGroups, canGrantUsers, onSignOut]);
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => void refresh(controller.signal), 200); return () => { clearTimeout(timer); controller.abort(); }; }, [refresh]);
  async function mutate(work: () => Promise<void>) { setError(""); try { await work(); setGroupId(""); setUserId(""); await refresh(); onChanged(); } catch (error) { if (error instanceof PermissionsRequestError && error.status === 401) onSignOut(); setError(errorMessage(error)); } }
  return <Dialog open fullWidth maxWidth="md" onClose={onClose} aria-labelledby="permission-grants-title"><DialogTitle id="permission-grants-title">Manage grants — {permission.name}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>
    <Alert severity="info">Grants are allow-only and additive. Changes are enforced by the backend on the next protected request.</Alert>{error && <Alert severity="error">{error}</Alert>}
    <TextField label="Search available targets" value={search} slotProps={{ htmlInput: { maxLength: 200 } }} onChange={(event) => setSearch(event.target.value)} />
    <Tabs value={tab} onChange={(_, value: "groups" | "users") => setTab(value)}><Tab label={`Groups (${grants.groups.length})`} value="groups"/><Tab label={`Direct users (${grants.users.length})`} value="users"/></Tabs>
    {tab === "groups" && <Stack spacing={1.5}>{canGrantGroups && permission.status === "ACTIVE" && <Stack direction={{ xs: "column", sm: "row" }} spacing={1}><TextField select fullWidth label="Active group" value={groupId} onChange={(event) => setGroupId(event.target.value)}>{groupCandidates.map((group) => <MenuItem key={group.id} value={group.id}>{group.name}</MenuItem>)}</TextField><Button variant="contained" disabled={!groupId || loading} onClick={() => mutate(() => grantGroupPermission(permission.id, groupId))}>Grant</Button></Stack>}{loading ? <Typography role="status">Loading grants…</Typography> : grants.groups.length === 0 ? <Typography role="status">No active group grants.</Typography> : grants.groups.map(({ group }) => <Stack direction="row" key={group.id} sx={{ alignItems: "center", justifyContent: "space-between" }}><Typography>{group.name} <Chip size="small" label={group.status.toLowerCase()} /></Typography>{canRevoke && <Button color="warning" onClick={() => mutate(() => revokeGroupPermission(permission.id, group.id))}>Revoke</Button>}</Stack>)}</Stack>}
    {tab === "users" && <Stack spacing={1.5}>{canGrantUsers && permission.status === "ACTIVE" && <Stack direction={{ xs: "column", sm: "row" }} spacing={1}><TextField select fullWidth label="Eligible user" value={userId} onChange={(event) => setUserId(event.target.value)}>{userCandidates.map((user) => <MenuItem key={user.id} value={user.id}>{user.firstName} {user.lastName} — {user.email}</MenuItem>)}</TextField><Button variant="contained" disabled={!userId || loading} onClick={() => mutate(() => grantUserPermission(permission.id, userId))}>Grant</Button></Stack>}{loading ? <Typography role="status">Loading grants…</Typography> : grants.users.length === 0 ? <Typography role="status">No active direct-user grants.</Typography> : grants.users.map(({ user }) => <Stack direction="row" key={user.id} sx={{ alignItems: "center", justifyContent: "space-between" }}><Typography>{user.firstName} {user.lastName}<br/><Typography component="span" color="text.secondary" variant="caption">{user.email}</Typography></Typography>{canRevoke && <Button color="warning" onClick={() => mutate(() => revokeUserPermission(permission.id, user.id))}>Revoke</Button>}</Stack>)}</Stack>}
  </Stack></DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>;
}

export function PermissionsPage({ currentUser, onSignOut }: { currentUser: AuthenticatedUser; onSignOut: () => void }) {
  const canRead = currentUser.permissions.includes("admin.permissions.read"); const canGrant = currentUser.permissions.includes("admin.permissions.grant"); const canRevoke = currentUser.permissions.includes("admin.permissions.revoke");
  const canGrantGroups = canGrant && currentUser.permissions.includes("admin.groups.read"); const canGrantUsers = canGrant && currentUser.permissions.includes("admin.users.read");
  const [pagination, setPagination] = useState<MRT_PaginationState>({ pageIndex: 0, pageSize: 20 }); const [sorting, setSorting] = useState<MRT_SortingState>([{ id: "category", desc: false }]);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [result, setResult] = useState<PermissionsResult | null>(null); const [loading, setLoading] = useState(canRead); const [error, setError] = useState(""); const [refresh, setRefresh] = useState(0); const [selected, setSelected] = useState<ManagedPermission | null>(null);
  useEffect(() => { if (!canRead) return; const controller = new AbortController(); const timer = setTimeout(() => { setLoading(true); setError(""); const sort = sorting[0]; listPermissions({ page: String(pagination.pageIndex + 1), pageSize: String(pagination.pageSize), search, sortBy: sort?.id ?? "category", sortOrder: sort?.desc ? "desc" : "asc", ...(status ? { status } : {}) }, controller.signal).then(setResult).catch((error) => { if (!controller.signal.aborted) { setError(errorMessage(error)); if (error instanceof PermissionsRequestError && error.status === 401) onSignOut(); } }).finally(() => !controller.signal.aborted && setLoading(false)); }, 250); return () => { clearTimeout(timer); controller.abort(); }; }, [canRead, pagination, sorting, search, status, refresh, onSignOut]);
  const columns = useMemo<MRT_ColumnDef<ManagedPermission>[]>(() => [
    { accessorKey: "name", header: "Permission", Cell: ({ row }) => <><Typography sx={{ fontSize: 13, fontWeight: 700 }}>{row.original.name}</Typography><Typography color="text.secondary" variant="caption">{row.original.permissionKey}</Typography></> },
    { accessorKey: "category", header: "Category" }, { accessorKey: "status", header: "Status", Cell: ({ row }) => <Chip size="small" label={row.original.status === "ACTIVE" ? "Active" : "Retired"} /> },
    { id: "groupGrants", header: "Groups", accessorFn: (row) => row._count.groupGrants, enableSorting: false }, { id: "userGrants", header: "Direct users", accessorFn: (row) => row._count.userGrants, enableSorting: false },
    { id: "actions", header: "Actions", enableSorting: false, Cell: ({ row }) => <Button onClick={() => setSelected(row.original)}>{canGrant || canRevoke ? "Manage grants" : "View grants"}</Button> },
  ], [canGrant, canRevoke]);
  return <Stack spacing={3}><PageHeader title="Permissions" description="Manage additive group and direct-user grants for the platform-defined permission catalogue." />
    {!canRead ? <Alert severity="info">You do not have permission to view the permission catalogue.</Alert> : <><Alert severity="info">Permission definitions are platform-managed. This screen manages grants only; explicit deny rules are not supported.</Alert><Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField fullWidth label="Search permissions" value={search} onChange={(event) => { setSearch(event.target.value); setPagination((value) => ({ ...value, pageIndex: 0 })); }} /><TextField select label="Status" value={status} sx={{ minWidth: 170 }} onChange={(event) => setStatus(event.target.value)}><MenuItem value="">All statuses</MenuItem><MenuItem value="ACTIVE">Active</MenuItem><MenuItem value="RETIRED">Retired</MenuItem></TextField><Button onClick={() => setRefresh((value) => value + 1)}>Refresh</Button></Stack>{error && <Alert severity="error">{error}</Alert>}<SaileAdminTable columns={columns} data={result?.data ?? []} getRowId={(row) => row.id} isLoading={loading} pagination={pagination} onPaginationChange={setPagination} sorting={sorting} onSortingChange={setSorting} rowCount={result?.meta.total ?? 0} />{!loading && !error && result?.meta.total === 0 && <Typography role="status">No permissions match these filters.</Typography>}</>}
    {selected && <GrantsDialog permission={selected} canGrantGroups={canGrantGroups} canGrantUsers={canGrantUsers} canRevoke={canRevoke} onClose={() => setSelected(null)} onSignOut={onSignOut} onChanged={() => setRefresh((value) => value + 1)} />}
  </Stack>;
}
